name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  
  # Icons
  cupertino_icons: ^1.0.8

  # Networking
  dio: ^5.4.0
  http: ^1.4.0

  # State management
  flutter_riverpod: ^2.4.9

  # Secure storage for auth tokens
  flutter_secure_storage: ^9.0.0

  # Navigation
  go_router: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/